services:
  front:
      image: node:23-alpine
      container_name: front-service
      working_dir: /usr/src/app
      ports:
        - "5173:5173"
      volumes:
        - ./front:/usr/src/app
      environment:
        - NODE_ENV=development
      entrypoint:
        - sh
        - -c
        - |
          npm install -g pnpm
          pnpm config set store-dir /home/node/.local/share/pnpm/store
          pnpm i
          pnpm run dev
      restart: unless-stopped

  report-service:
    image: node:23-alpine 
    container_name: report-service
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    volumes:
      - ./report-service:/usr/src/app
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_DB=reportdb
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - S3_ENDPOINT=minio
      - S3_PORT=9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=reports
    depends_on:
      - postgres
      - minio
    entrypoint: 
      - sh
      - -c
      - |
        npm install -g pnpm
        pnpm config set store-dir /home/node/.local/share/pnpm/store
        pnpm i
        pnpm run migration:run
        pnpm run start:dev
    restart: unless-stopped

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: reportdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
  minio-data:
